### ISSUE TITLE
osm2po parser skipping edges

### ISSUE THREAD

**Issue by 09saurabh09** [pgRouting/pgrouting-contrib#5]
Using osm2po for parsing osm data and importing to postgresql is too easy but when i look at database and draw all the edges i find out some of the edges are missed so that the roads are not smooth, i don't know why this is happening, if anyone here can help me please do so i am in big trouble

**Comment by dkastl** [comment]
Sorry, but osm2po is not an Open Source project and there is nothing we can do about it.
You had to contact the person developing osm2po directly.
