### ISSUE TITLE
sp_smart_directed error

### ISSUE THREAD

**Issue by mfhanif** [pgRouting/pgrouting-contrib#6]
Hey guys i'm new in pgrouting and i just found the wrapper that i thought it will help me a lot to accomplish my point to point routing. when i started to load the https://github.com/pgRouting/pgrouting-contrib/blob/master/functions-v1.x/routing_core_smart.sql in my postgres, it brought me a lot of error and most of them are the function which not recognized by postgis. But the solution is easy, just add "st_" infront of the function (e.g: distance -> st_distance)
my question is when i finished fix that errors and start to do some routing, it gave me an error like

ERROR: query string argument of EXECUTE is null
SQL state: 22004
Context: PL/pgSQL function sp_smart_directed(character varying,boolean,double precision,double precision,double precision,double precision,double precision,character varying,character varying,boolean,boolean) line 309 at FOR over EXECUTE statement

it happened when i choose point in different way or vertex or its long way to route, but if its just in the same way it gave me a result that i want like

id;gid;the_geom
0;459198;"0102000020E6100000020000001DA3510658B45A403E95006A90C318C0BB73ED0D58B45A40A0FDD42D9FC318C0"
1;459194;"0105000020E6100000010000000102000000030000007201674648B45A40F4FEACE7ADC318C0EE5F596952B45A4066DD3F16A2C318C0B773ED0D58B45A40A2FDD42D9FC318C0"
2;459199;"0102000020E6100000020000007101674648B45A40F8FEACE7ADC318C0F0A2513448B45A40B0B801659EC318C0"

please help me to solve this problem, i'm dying for a couple days to find out this things done
before that, i'm sorry for my bad english and my noob

regards, 
Hanif

**Comment by dkastl** [comment]
I guess you have these errors because the wrapper function was written for the old version of pgRouting and you're now using version 2.0, which does not contain "Shooting Star" algorithm anymore and has been replaced by TRSP algorithm.

So the wrapper function is currently only useful as an example to study how to write plpgsql functions, ut you had to write your own one.

**Comment by mfhanif** [comment]
ouch, ok thanks for the clarity dkasti
